# OSBasicSettings2.yml
---
- hosts: win
  collections:
    - ansible.windows
  gather_facts: no
  vars_files:
    - params2.yml
  tasks:
    - name: Initialize a disk
      community.windows.win_initialize_disk:
        disk_number: "{{ disk_number }}"

    - name: Create a partition
      community.windows.win_partition:
        drive_letter: "{{ drive_letter }}"
        partition_size: "{{ partition_size }}"
        disk_number: "{{ disk_number }}"

    - name: Format Partition
      community.windows.win_format:
        drive_letter: "{{ drive_letter }}"
        file_system: "{{ filesystem_type }}"
        new_label: DATA
        full: True

    - name: Move paging file to C:\ drive
      win_pagefile:
        drive: "C:"  # Move paging file to C:\ drive

    - name: Move paging file to temporary storage drive
      win_pagefile:
        drive: "{{ temporary_drive_letter }}"
      when: temporary_drive_letter is defined

    - name: Install SNMP Service
      win_feature:
        name: SNMP-Service
        state: present

    - name: Configure Remote Desktop settings
      win_shell: |
        # Disable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 1 -Force

        # Allow Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force

        # Allow connections only from computers running Remote Desktop with Network Level Authentication (NLA)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force
      when: enable_remote_desktop is defined and enable_remote_desktop

    - name: Configure Windows Defender Firewall
      win_shell: |
        # Turn on Windows Defender Firewall for Domain, Public, and Private profiles
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
      when: enable_firewall is defined and enable_firewall

    - name: Restart the system to apply changes
      win_reboot:
        reboot_timeout: 300
        msg: "Rebooting to apply changes"
