# OSBasicSettings.yml
---
- name: OS Basic Settings Configuration
  hosts: win
  gather_facts: true
  tasks:
    - name: Include variables
      include_vars:
        file: param.yml

    - name: Change computer name
      win_hostname:
        name: "{{ computer_name }}"

    - name: Set domain or workgroup name
      win_domain_membership:
        workgroup: "{{ workgroup_name }}"
        domain_name: "{{ domain_name }}"
        state: "{{ 'workgroup' if workgroup_name else 'domain' }}"

    - name: Set primary DNS suffix
      win_dns_client:
        primary_dns_suffix: "{{ primary_dns_suffix }}"

    - name: Check activation status
      win_shell: slmgr /xpr
      register: activation_status

    - name: Display activation status
      debug:
        msg: "Activation Status: {{ activation_status.stdout_lines[0] }}"
