#OSBasicSettings2.yml
- 
  hosts: win
  tasks:
    - name: Initialize disk
      win_disk_image:
        disk_number: "{{ disk_number }}"  # Specify the disk number
        initialize: yes
        offline: yes

    - name: Create partition
      win_disk_image:
        disk_number: "{{ disk_number }}"  # Specify the disk number
        partition_size: "{{ partition_size }}"  # Specify the partition size
        offline: yes
        drive_letter: "{{ drive_letter }}"  # Specify the desired drive letter
        state: present

    - name: Format partition
      win_format:
        drive_letter: "{{ drive_letter }}"  # Specify the drive letter
        fs_type: "{{ filesystem_type }}"  # Specify the filesystem type, e.g., NTFS
        confirm: yes

    - name: Mount partition
      win_disk_image:
        disk_number: "{{ disk_number }}"  # Specify the disk number
        drive_letter: "{{ drive_letter }}"  # Specify the drive letter
        mount_path: "{{ mount_path }}"  # Specify the mount path
        offline: yes
        state: present

    - name: Move paging file to C:\ drive
      win_pagefile:
        drive: "C:"  # Move paging file to C:\ drive

    - name: Change drive letter
      win_disk_partition:
        disk_number: "{{ disk_number }}"  # Specify the disk number
        partition_number: 1  # Assuming it's the first partition on the disk
        drive_letter: "{{ new_drive_letter }}"  # Specify the new drive letter
		
	- name: Move paging file to temporary storage drive
      win_pagefile:
        drive: "{{ temporary_drive_letter }}"
	
	- name: Install SNMP Service
      win_feature:
        name: SNMP-Service
        state: present
		
	- name: Configure Remote Desktop settings
      win_shell: |
        # Disable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 1 -Force

        # Allow Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force

        # Allow connections only from computers running Remote Desktop with Network Level Authentication (NLA)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force
	
	- name: Configure Windows Defender Firewall
      win_shell: |
        # Turn on Windows Defender Firewall for Domain, Public, and Private profiles
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True

        # OR, to turn off Windows Defender Firewall for Domain, Public, and Private profiles
        # Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

    - name: Restart the system to apply changes
      win_reboot:
        reboot_timeout: 300
        msg: "Rebooting to apply changes"
