# OSBasicSettings.yml
---
- hosts: win
  collections:
    - ansible.windows
  gather_facts: no
  vars_files:
    - params.yml
  tasks:
    - name: Set Computer Name
      win_shell: |
        $ComputerInfo = Get-WmiObject Win32_ComputerSystem
        $ComputerInfo.Rename("{{ computer_name }}")

    - name: Check Domain Membership
      win_shell: |
        $ComputerInfo = Get-WmiObject Win32_ComputerSystem
        $ComputerInfo.PartOfDomain
      register: domain_status

    - name: Join Domain
      win_domain_membership:
        hostname: "{{ computer_name }}"
        domain_name: "{{ domain_name }}"
        username: "{{ domain_admin_username }}"
        password: "{{ domain_admin_password }}"
        state: domain
      when: "not domain_status.stdout"
      register: reboot_result

    - name: Check Workgroup Membership
      win_shell: |
        (Get-WmiObject Win32_ComputerSystem).Workgroup
      register: workgroup_status

    - name: Join Workgroup
      win_domain_membership:
        hostname: "{{ computer_name }}"
        workgroup: "{{ workgroup_name }}"
        state: workgroup
      when: "not domain_status.stdout and not workgroup_status.stdout"
      register: reboot_result

    - name: Set Primary DNS Suffix
      win_shell: |
        Set-DnsClientGlobalSetting -SuffixSearchList "{{ primary_dns_suffix }}"
      register: dns_suffix_result

    - name: Get current primary DNS suffix setting
      win_reg_stat:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters"
        name: "SyncDomainWithMembership"
      register: dns_suffix_setting

    - name: Enable/disable primary DNS suffix change
      win_regedit:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters"
        name: "SyncDomainWithMembership"
        data: "{{ enable_primary_dns_suffix }}"
        type: dword
      when: dns_suffix_setting.exists | default(false) and dns_suffix_setting.value != enable_primary_dns_suffix

    - name: Set automatic updates option
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
        data: 0
        type: dword
        state: present

    - name: Set scheduled install day and time
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
        data: "{{ ScheduledInstallDay }}"
        type: dword
        state: present

    - name: Set scheduled install time
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
        data: "{{ ScheduledInstallTime }}"
        type: string
        state: present

    - name: Install updates for other Microsoft products
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
        name: AcceptTrustedPublisherCerts
        data: "{{ AcceptTrustedPublisherCerts }}"
        type: dword
        state: present

    - name: Install during automatic maintenance
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AlwaysAutoRebootAtScheduledTime
        data: 1
        type: dword
        state: present

    - name: Configure Windows Update Settings (Advanced Options)
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update"
        name: "AUOptions"
        data: "3"
        type: dword

    - name: Configure Windows Update for Other Microsoft Products
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate"
        name: "IncludeRecommendedUpdates"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Download Updates Over Metered Connections
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DeliveryOptimization\\Config"
        name: "DODownloadMode"
        data: "{{ zero_value }}"
        type: dword

    - name: Configure Update Notifications
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\UX\\Settings"
        name: "UxOption"
        data: "2"
        type: dword

    - name: Configure Pause Updates
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings"
        name: "PauOptions"
        data: "2"
        type: dword

    - name: Configure Real-time Protection
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection"
        name: "DisableRealtimeMonitoring"
        data: "{{ zero_value }}"
        type: dword
      when: "not domain_status.stdout and not workgroup_status.stdout"

    - name: Configure Cloud-based Protection
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\SpyNet"
        name: "SpynetReporting"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Automatic Sample Submission
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet"
        name: "SubmitSamplesConsent"
        data: "{{ one_value }}"
        type: dword
      when: "not domain_status.stdout and not workgroup_status.stdout"

    - name: Configure Controlled Folder Access
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Exploit Guard\\Controlled Folder Access"
        name: "EnableControlledFolderAccess"
        data: "{{ one_value }}"
        type: dword
      when: "not domain_status.stdout and not workgroup_status.stdout"

    - name: Check if files exist
      win_stat:
        path: "{{ item }}"
      loop: "{{ files_to_exclude }}"
      register: file_stat_result

    - name: Add exclusions for files
      win_command: >
        Add-MpPreference -ExclusionPath "{{ item }}"
      loop: "{{ file_stat_result.results }}"
      when: item.stat.exists
      register: file_exclusions_result
      ignore_errors: true

    - name: Check if folders exist
      win_stat:
        path: "{{ item }}"
      loop: "{{ folders_to_exclude }}"
      register: folder_stat_result

    - name: Add exclusions for folders
      win_command: >
        Add-MpPreference -ExclusionPath "{{ item }}"
      loop: "{{ folder_stat_result.results }}"
      when: item.stat.exists
      register: folder_exclusions_result
      ignore_errors: true

    - name: Check if processes exist
      win_shell: >
        Get-Process -Name "{{ item }}" -ErrorAction SilentlyContinue
      loop: "{{ processes_to_exclude }}"
      register: process_check_result
      failed_when: false

    - name: Set apps and files
      win_shell: |
        Set-MpPreference -PUAProtection: "{{ apps_files_policy }}"
      args:
        executable: powershell.exe
      register: app_file_result

    - name: Enable Exploit Protections
      win_shell: |
        {% for protection in exploit_protections %}
        Set-ProcessMitigation -System -Enable {{ protection }}
        {% endfor %}
      become: yes
      become_user: "{{ admin_user }}"

    - name: Configure Memory Integrity
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer"
        name: "DeviceGuard\\EnableVirtualizationBasedSecurity"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Optional Diagnostic Data
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Diagnostic\\"
        name: "AllowTelemetry"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Improve Inking and Typing
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\PenWorkspace"
        name: "PenWorkspace\\PenFeedbackEnabled"
        data: "{{ one_value }}"
        type: dword

    - name: Configure View Diagnostic Data
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Privacy"
        name: "DeviceName\\PublishUserActivities"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Feedback Frequency
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Feedback"
        name: "Feedback\\FeedbackFrequency"
        data: "{{ one_value }}"
        type: dword

    - name: Configure Diagnostic & Feedback Settings
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection"
        name: "AllowTelemetry"
        data: "{{ zero_value }}"
        type: dword

    - name: Configure Internet Explorer Enhanced Security Configuration (IE ESC)
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components\\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}"
        name: "IsInstalled"
        data: "{{ zero_value }}"
        type: dword

    - name: Configure Internet Explorer Enhanced Security Configuration for Administrators
      win_regedit:
       key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
       name: "IEHardenAdmin"
       data: "{{ one_value }}"
       type: dword

    - name: Configure Internet Explorer Enhanced Security Configuration for Users
      win_regedit:
       key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
       name: "IEHarden"
       data: "{{ one_value }}"
       type: dword

    - name: Enable Remote Desktop
      win_regedit:
        path: "{{ registry_path }}"
        name: "{{ registry_name }}"
        data: "{{ registry_value }}"
        type: dword

    - name: Allow Remote Desktop through Firewall for Domain
      win_firewall_rule:
        name: "{{ firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: domain

    - name: Allow Remote Desktop through Firewall for Private
      win_firewall_rule:
        name: "{{ firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: private

    - name: Allow Remote Desktop through Firewall for Public
      win_firewall_rule:
        name: "{{ firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: public

    - name: Enable PowerShell Remoting
      win_shell: "{{ ps_remoting_command }}"

    - name: Allow ICMP (for ping) through Firewall for Domain
      win_firewall_rule:
        name: "{{ icmp_firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: domain

    - name: Allow ICMP (for ping) through Firewall for Private
      win_firewall_rule:
        name: "{{ icmp_firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: private

    - name: Allow ICMP (for ping) through Firewall for Public
      win_firewall_rule:
        name: "{{ icmp_firewall_rule_name }}"
        enable: yes
        direction: in
        action: allow
        profile: public

    - name: Check Activation Status
      win_shell: |
        (Get-CimInstance -ClassName SoftwareLicensingProduct -Filter "Name like 'Windows%'").LicenseStatus
      register: activation_status

    - name: Configure Server Manager Properties
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\ServerManager"
        name: "DoNotOpenServerManagerAtLogon"
        data: "{{ one_value }}"
        type: dword

    - name: Set RegisteredOwner
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
        name: RegisteredOwner
        data: "{{ registered_owner }}"
        type: string

    - name: Set RegisteredOrganization
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
        name: RegisteredOrganization
        data: "{{ registered_organization }}"
        type: string

    - name: Choose or Customize a Power Plan
      win_shell: |
        powercfg -setactive "{{ power_plan }}"

    - name: Set Time to Turn Off Display (in minutes)
      win_shell: |
        powercfg -change -monitor-timeout-ac "{{ minutes_ac_timeout}}"
        powercfg -change -monitor-timeout-dc "{{ minutes_dc_timeout }}"

    - name: Set Time to Put Computer to Sleep (in minutes)
      win_shell: |
        powercfg -change -standby-timeout-ac "{{ minutes_ac_sleep }}"
        powercfg -change -standby-timeout-dc "{{ minutes_dc_sleep }}"

    - name: Create Windows Group Account
      ansible.windows.win_group:
        name: "{{ new_group_name }}"
        description: "{{ group_description }}"
        state: present

    - name: Create Windows User Account
      ansible.windows.win_user:
        name: "{{ user_name }}"
        fullname: "{{ full_name }}"
        description: "{{ user_description }}"
        password: "{{ user_password }}"
        state: present
        password_expired: no
        password_never_expires: yes
        groups: "{{ new_group_name }}"


    - name: Reboot the machine
      win_reboot:
      async: 0
      poll: 0
      register: reboot_result
