# OSBasicSettings2.yml
---
- hosts: win
  collections:
    - ansible.windows
  gather_facts: no
  vars_files:
    - params2.yml
  tasks:
    - name: Initialize and format disk in Windows
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Initialize disk
      win_disk_partition:
        disk_number: "{{ disk_number }}"
        partition_style: "{{ partition_style }}"
      register: disk_initialized
      changed_when: disk_initialized.changed

    - name: Get disk facts
      win_disk_facts:
        disk_number: "{{ disk_number }}"
      register: disk_info

    - name: Create partition
      win_partition:
        disk_number: "{{ disk_number }}"
        size: "{{ disk_info.disks[disk_number].size | default('UseMaximumSize') }}"
      when: disk_initialized.changed
      register: partition_created
      changed_when: partition_created.changed

    - name: Format partition
      win_format:
        disk: "{{ disk_number }}"
        partition: "{{ disk_info.partitions[0].partition_number }}"
        fs: "{{ filesystem }}"
        label: "{{ volume_label }}"
      when: partition_created.changed
      changed_when: false

    - name: Assign drive letter
      win_disk_facts:
        disk_number: "{{ disk_number }}"
        include_partitions: yes
      register: disk_facts

    - name: Set drive letter
      win_disk_facts:
        disk_number: "{{ disk_number }}"
        partition_number: "{{ disk_facts.partitions[0].partition_number }}"
        drive_letter: "{{ drive_letter }}"
      when: partition_created.changed

    - name: Move paging file to C:\ drive
      win_pagefile:
        drive: "C:"  # Move paging file to C:\ drive

    - name: Move paging file to temporary storage drive
      win_pagefile:
        drive: "{{ temporary_drive_letter }}"
      when: temporary_drive_letter is defined

    - name: Install SNMP Service
      win_feature:
        name: SNMP-Service
        state: present

    - name: Configure Remote Desktop settings
      win_shell: |
        # Disable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 1 -Force

        # Allow Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force

        # Allow connections only from computers running Remote Desktop with Network Level Authentication (NLA)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force
      when: enable_remote_desktop is defined and enable_remote_desktop

    - name: Configure Windows Defender Firewall
      win_shell: |
        # Turn on Windows Defender Firewall for Domain, Public, and Private profiles
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
      when: enable_firewall is defined and enable_firewall

    - name: Set Processor Scheduling
      win_regedit:
        path: "{{ registry_processor }}"
        name: "{{ registry_name_processor }}"
        data: "{{ services_value }}"
        type: "{{ registry_type_proc }}"
        state: present

    - name: Enable or Disable Pagefile
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
        name: PagingFiles
        data: "{{ 'Auto' if enable_auto_manage else drive_letter_page + ' ' + initial_size_mb + ' ' + maximum_size_mb }}"
        type: string
      when: enable_auto_manage != ('Auto' in pagingfiles_reg.data|default([]))

    - name: Get current state of PagingFiles registry value
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
        name: PagingFiles
      register: pagingfiles_reg

    - name: Set Timeout for Boot Menu
      win_command: bcdedit /timeout 10

    - name: Configure Automatic Restart upon System Failure
      win_command: bcdedit /set {default} bootstatuspolicy ignoreallfailures

    - name: Enable Writing of Event Logs upon System Failure
      win_command: bcdedit /set {default} recoveryenabled yes

    - name: Verify Changes
      win_command: bcdedit

    - name: Restart the system to apply changes
      win_reboot:
        reboot_timeout: 300
        msg: "Rebooting to apply changes"
